### PR TITLE
STATIC_ROOT set

### PR DESCRIPTION
**Pull request by GouravSardana**
There is a problem in improper configuration due to this static_root.
You can check and do changes on the server.

### CODE REVIEW

**Comment by avinashbharti97** [comment]
Adding STATIC_ROOT is handy in serving static files in Production settings and works with collectstatic command.

So I think for the development setting it is better to only add the Staticfiles_dir by doing this Django will see the static files in static folder only.

Please keep your point why we need this for now.

Also, It is better to open an issue first rather than making a direct pull request :)

**Comment by GouravSardana** [comment]
But the site server is not working you can check on your server https://sugarsocial.herokuapp.com/

**Comment by avinashbharti97** [comment]
@GouravSardana  Please ignore that link, Hosting on Heroku server is not synced with this GitHub repo.

**Comment by GouravSardana** [comment]
Okay 
So, I am closing the PR.

**Pull request closed without merging**
