### PR TITLE
Fixing position of side Navigation Menu

### PR DESCRIPTION
**Pull request by FreddieN**
I have adjusted the CSS for the Navbar and implemented some JS to allow the navbar to be fixed to the side of the page when a user is scrolling. (see gif)

https://i.imgur.com/RjMOleA.gif

Let me know if any issues :)
Freddie

### CODE REVIEW

**Comment by avinashbharti97** [comment]
I think it will be good to fix the top nav and the tags div with the side nav too.
and this code causing x-overflow in mobile view.
ps:- feel free to use your own creativity that could not be mentioned in the task do what suits best

**Comment by FreddieN** [comment]
I've fixed the top nav and improved the mobile view: https://i.imgur.com/YUVeN0B.gif
Could you let me know what you meant by x-overflow in mobile view? (a screenshot maybe)
Thank you :)

**Comment by FreddieN** [comment]
Also while doing some mobile optimisation I noticed the card images were quite compact:
https://i.imgur.com/ehZ4Dk7.png
I suggest we get them to span the whole width in mobile view like this:
https://i.imgur.com/miGqLzq.png
This isn't really part of the navigation so I haven't made any edits to it.

**Comment by avinashbharti97** [comment]
@FreddieN  Yes, I am aware of that image width bug and it will be so helpful if you will fix that :D

**Comment by avinashbharti97** [comment]
@FreddieN  last pull is creating some bugs:-
- all Links are not working
- you can see the change in padding and position of side nav when shifting between two menu options

I think there are more bugs there, I will come again after checking it thoroughly.

**Comment by FreddieN** [comment]
Links are now fixed, sorry I really should have spotted that... Can you send me a screenshot of what you mean by the change in padding?
Thank you :)
Also I will fix the mobile cards later.

**Comment by avinashbharti97** [comment]
@FreddieN  Almost everything is fixed except some issues:-

- padding or margin of left menu bar problem on shifting between menu.
peek 2018-11-04 12-42

- I think Fixing the position of featured tag section is a good idea.
tag

**Comment by FreddieN** [comment]
Updated with these changes. See screenshot:
Demo Gif
I think that it is now bug-free :)

**Review by divyanshu-rawat — COMMENTED** [review]
@FreddieN Nice Work 😃

**Comment by avinashbharti97** [comment]
@FreddieN  I can't see the fix, It is still there.

bug2

I think unknowingly you just change the spacing of cards or something else.

- Before Fix
before_fix

- After Your Fix
after_fix

**Comment by FreddieN** [comment]
Ah sorry, I thought you were talking about this space:
d
That's why I updated the card spacing for all pages. I've reverted that.
Here is the actual navigation fixed:
d

**Comment by avinashbharti97** [comment]
@FreddieN  Please check after disabling cache :)
bug3

**Comment by FreddieN** [comment]
[demo](https://i.imgur.com/OQQa14T.gif)
@avinashbharti97 quick fix :)

**Comment by avinashbharti97** [comment]
Some more fixes require:-
1. add username linked wtih their profile in mobile view
menu

2. You didn't fix the extra spacing of feed cards, Try to keep the spacing as before.
     - fix the spacing of posts card (blogs cards in feed is okay)
     - move featured tags section to the right as before
window



** Please discuss the changes you are going to make, before coding or implementing(i.e idea of new mobile view menu bar).
Try to explain the changes you did with each PR in comments.

** Do not assume anything by yourself, In case of misunderstandings please clear the things!

Thanks

**Comment by FreddieN** [comment]
I've committed these fixes. Sorry about not discussing the mobile navigation, I found it in the root folder and thought it looked cleaner than the desktop navigation on mobile. If you want I can switch it back?
demo
demo

**Comment by avinashbharti97** [comment]
@FreddieN  I liked the Navigation bar of mobile view :)
Everything is working fine and smooth now :D and you did a very good job.
Thank you :)
Wish you All the best.

**Comment by FreddieN** [comment]
Glad I got it how you wanted it :D

**Pull request merged**
